### ISSUE TITLE
Exercise 8 Tests with different references

### ISSUE THREAD

**Issue by Dev24** [ChristophP/node-fp-coding-dojo#13]
The failedTask - rejects test is not checking for the returned value.
The mappedTask -resolved with 8 test is referring to a different variable.
The getRandom test should is referring to a different variable.

**Comment by Dev24** [comment]
I've submitted a pull request with the fixes.

**Comment by ChristophP** [comment]
Thanks for fixing @Dev24

**Comment by Dev24** [comment]
Welcome. Thanks for the DOJO Chris, much appreciated!
